### ISSUE TITLE
Can support for VMPROTECT be added?

### ISSUE THREAD

**Issue by icyfox168168** [MahmoudZohdy/DLL-Obfuscation-V2#1]
Can support for VMPROTECT be added?

**Comment by MahmoudZohdy** [comment]
what do you mean by support for VMPROTECT? if the DLL at FIXED address it should load normally.

**Comment by icyfox168168** [comment]
The dll file encrypted with vmprotect cannot be loaded normally, and none can be loaded normally

**Comment by icyfox168168** [comment]
DLL-Obfuscation-V2.exe 1 TestDll.vmp.dll f.dll  //Failed to encrypt f.dll

DLL-Obfuscation-V2.exe 2 f.dll // ok

pause

**Comment by MahmoudZohdy** [comment]
so when the file is obfuscated with vmprotect DLL-Obfuscation-V2.exe fails to encrypt it, or it fails to load the encrypted DLL ?

**Comment by icyfox168168** [comment]
Remove the decryption function and directly load TestDll.vmp.dll is normal operation, very ideas and code

**Comment by MahmoudZohdy** [comment]
so you try to load TestDll.vmp.dll (obfuscated using vmprotect) and not encrypted with DLL-Obfuscation-V2.exe but the decryption part is removed from it before loading?

when you do that it pause right?

**Comment by icyfox168168** [comment]
Yes, this operation is correct, it is the problem of encrypting the code segment, the program recognizes the problem of the code segment encrypted by vmp

**Comment by MahmoudZohdy** [comment]
as for my understanding of vmprotect, it should virtualize part of the code not encrypt the code segment.

can you tell me what part of the encryption did you removed (as there is two loops)?

**Comment by icyfox168168** [comment]
I just removed the encryption and decryption function. I directly tested your program architecture. It is correct. It can be loaded correctly and the hardware breakpoint function can be successfully intercepted.

**Comment by MahmoudZohdy** [comment]
so you are asking if it can load DLL protected using vmprotect without any encryption or decryption, just loading it?

is my understanding of your issue is correct?, and did you try it and failed?

**Comment by icyfox168168** [comment]
The f file cannot be encrypted. I skip this function and test the hardware to intercept the loaded dll. This function can pop up a dialog box. If vmp is not added, everything is correct.

DLL-Obfuscation-V2.exe 1 TestDll.vmp.dll f.dll

DLL-Obfuscation-V2.exe 2 TestDll.vmp.dll

pause


		DWORD64* MapBase = (DWORD64*)(*pBaseAddress);
		DWORD64* Start = MapBase;
		//EncryptDecryptCodeSection((BYTE*)Start, 0);

		MessageBoxA(0, 0, 0, 0);

**Comment by MahmoudZohdy** [comment]
so when you try to encrypt TestDll.vmp.dll to file f.dll it fails, and when you try to load TestDll.vmp.dll without any decryption it work normally.

is this behavior happen with all vmprotect dll ?

**Comment by icyfox168168** [comment]
The version of vmprotect I use is 3.5, and I only test the example DLL file in your project file

**Comment by MahmoudZohdy** [comment]
so you did not test encrypt and load vmprotect DLL?

**Comment by icyfox168168** [comment]
Tested, added VMP shell, you need to remove the encryption and decryption function to be normal, because the code segment cannot be encrypted

**Comment by MahmoudZohdy** [comment]
is the code segment relocatable ?

**Comment by icyfox168168** [comment]
Unable to create encrypted dll, maybe you identified a bug in the code segment, you can generate encrypted dll without adding VMPROTECT

**Comment by MahmoudZohdy** [comment]
i have assumed that the code segment name will be **text** or **code** i think that VMP name the code section differently.

can you check the code section name using any tool that parse PE header like **CFF explorer** ?

**Comment by icyfox168168** [comment]
.vmp1

**Comment by icyfox168168** [comment]
Modify here to generate encrypted dll, but the load is detected by vmp crc error

		char pSectionName[] = "text";
		char* pch;
		pch = strstr((CHAR*)pSourceImage->Sections[x].Name, ".vmp1");
		if (pch == NULL) {
			pch = strstr((CHAR*)pSourceImage->Sections[x].Name, "code");
			if (pch == NULL)
				continue;

**Comment by MahmoudZohdy** [comment]
this is the reason why it did not encrypt code section of VMPROTECT DLL, the code section name is different, you can change the code with the to edit the section name it looks for **text**->**vmp1** 
the function to change is **EncryptDecryptCodeSection** inside **Utiliti.h**

i only supported **text** and **code** as they are the normal name of code section 

let me know it it works with you.

**Comment by MahmoudZohdy** [comment]
so it was able to encrypt, but the load the encrypted DLL has some error?

is the DLL relocatable?

**Comment by icyfox168168** [comment]
Remove the crc option when packing, everything is normal

**Comment by MahmoudZohdy** [comment]
great let me know if you faced another issue.
